# Generated by Django 4.2.27 on 2026-02-02 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del producto', max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(help_text='Proporcione una descripción detallada del producto', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio (COP)')),
                ('stock', models.IntegerField(help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('imagen', models.ImageField(blank=True, help_text='Opcional: Cargue una imagen representativa', null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre descriptivo de la promoción', max_length=100, verbose_name='Título de la Promoción')),
                ('descripcion', models.TextField(help_text='Explique los detalles de la promoción', verbose_name='Descripción')),
                ('descuento', models.IntegerField(help_text='Ingrese un número entre 1 y 100', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Porcentaje de Descuento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del servicio', max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(help_text='Describe qué incluye y en qué consiste el servicio', verbose_name='Descripción')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base en pesos colombianos', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio Base (COP)')),
                ('duracion_estimada', models.CharField(help_text='Ej: 2 horas, 3 días, 1 semana', max_length=50, verbose_name='Duración Estimada')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
