# Generated by Django 4.2.27 on 2026-02-20 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoweb',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Catálogo Web', 'verbose_name_plural': 'Catálogos Web'},
        ),
        migrations.AlterField(
            model_name='productoweb',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El precio debe ser mayor a $0.'), django.core.validators.MaxValueValidator(9999999.99, message='El precio no puede superar $9,999,999.99.')], verbose_name='Precio Público'),
        ),
    ]
