# Generated by Django 4.2.27 on 2026-02-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0004_remove_proveedor_cc_encargado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0006_remove_producto_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_repartidor', models.CharField(max_length=150)),
                ('apellido_repartidor', models.CharField(max_length=150)),
                ('cedula_repartidor', models.CharField(max_length=20)),
                ('telefono_repartidor', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Proveedores.proveedor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
