# Generated by Django 4.2.27 on 2026-02-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_remove_producto_cantidad'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Productos.producto')),
            ],
        ),
    ]
