# Generated by Django 4.2.27 on 2026-02-04 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_producto_cantidad'),
        ('Proveedores', '0003_alter_proveedor_options_alter_proveedor_cc_encargado_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_repartidor', models.CharField(max_length=150)),
                ('apellido_repartidor', models.CharField(max_length=150)),
                ('cedula_repartidor', models.CharField(max_length=20)),
                ('telefono_repartidor', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='Proveedores.proveedor')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
    ]
