# Generated by Django 4.2.27 on 2026-02-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_detallemovimiento_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleMovimiento',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
    ]
