# Generated by Django 4.2.27 on 2026-02-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
