# Generated by Django 4.2.27 on 2026-02-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
        ('inventario', '0003_remove_movimientoinventario_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ultima_entrada_cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ultima_entrada_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ultima_entrada_precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='ultimo_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Proveedores.proveedor'),
        ),
    ]
