# Generated by Django 4.2.27 on 2026-02-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_stock_ultima_entrada_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ultima_entrada_cantidad',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ultima_entrada_fecha',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ultima_entrada_precio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ultimo_proveedor',
        ),
    ]
