# Generated by Django 6.0.3 on 2026-03-16 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título corto de la notificación', max_length=120)),
                ('mensaje', models.TextField(help_text='Cuerpo del mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('danger', 'Error / Alerta')], default='info', max_length=10)),
                ('leida', models.BooleanField(default=False, help_text='True cuando el usuario ya la vio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibirá la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
