# Generated by Django 4.2.27 on 2026-02-01 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_venta', models.CharField(editable=False, max_length=10, unique=True)),
                ('codigo_producto', models.CharField(max_length=50, verbose_name='Código producto / servicio')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('codigo_colaborador', models.CharField(max_length=20, verbose_name='Código colaborador')),
                ('nombre_colaborador', models.CharField(max_length=150, verbose_name='Nombre colaborador')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
    ]
