# Generated by Django 4.2.27 on 2026-02-05 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('servicios', '0001_initial'),
        ('Productos', '0005_alter_producto_cantidad'),
        ('ventas', '0002_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='colaborador_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.personal'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('anulada', 'Anulada')], default='activa', max_length=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Productos.producto'),
        ),
    ]
