# Generated by Django 4.2.27 on 2026-02-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detalleventa_colaborador_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='estado',
        ),
    ]
