# Generated by Django 4.2.27 on 2026-02-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio_unitario',
        ),
    ]
