# Generated by Django 4.2.27 on 2026-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto que se muestra en la tarjeta pública', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='etiqueta',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('especial', 'Especial'), ('limitado', 'Limitado'), ('descuento', 'Descuento'), ('exclusivo', 'Exclusivo')], default='nuevo', help_text='Badge visible en la web pública', max_length=20, verbose_name='Etiqueta'),
        ),
    ]
