# Generated by Django 4.2.27 on 2026-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_promocion_descripcion_promocion_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/', verbose_name='Imagen'),
        ),
    ]
