# Generated by Django 4.2.27 on 2026-03-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, help_text='Valor entre 1 y 100', max_digits=5, verbose_name='% de Descuento'),
        ),
    ]
