# Generated by Django 4.2.27 on 2026-03-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='servicios/videos/', verbose_name='Video del Servicio'),
        ),
    ]
