# Generated by Django 4.2.27 on 2026-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_gestionalisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionalisado',
            name='tipo_alisado',
            field=models.TextField(verbose_name='Tipo de alisado a realizar'),
        ),
    ]
