# Generated by Django 4.2.27 on 2026-02-05 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_gestionalisado_tipo_alisado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionalisado',
            name='anticipo_cliente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo realizado por el cliente'),
        ),
        migrations.AlterField(
            model_name='gestionalisado',
            name='precio_alisado',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del Alisado'),
        ),
        migrations.AlterField(
            model_name='gestionalisado',
            name='saldo_pendiente',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo pendiente por pagar'),
        ),
    ]
