# Generated by Django 4.2.27 on 2026-02-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_delete_clientes'),
        ('servicios', '0004_alter_gestionalisado_anticipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionalisado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_alisado', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
