# Generated by Django 4.2.27 on 2026-02-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestionalisado',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Gestion de datos', 'verbose_name_plural': 'Gestion de datos'},
        ),
    ]
