# Generated by Django 4.2.27 on 2026-02-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_gestionalisado_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GestionAlisado',
        ),
    ]
