# Generated by Django 6.0.3 on 2026-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='whatsapp_key',
            field=models.CharField(blank=True, help_text='API Key de CallMeBot para recibir alertas por WhatsApp', max_length=20, null=True, verbose_name='CallMeBot API Key'),
        ),
    ]
