# Generated by Django 4.2.27 on 2025-12-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='documento',
            field=models.CharField(blank=True, help_text='Número de documento de identidad', max_length=20, null=True, unique=True),
        ),
    ]
