# Generated by Django 4.2.27 on 2026-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_documento',
            field=models.CharField(choices=[('tarjeta_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='cedula', help_text='Tipo de documento de identidad', max_length=20),
        ),
    ]
