# Generated by Django 4.2.27 on 2026-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='recovery_code',
            field=models.CharField(blank=True, help_text='Código de recuperación de contraseña', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='recovery_code_created',
            field=models.DateTimeField(blank=True, help_text='Fecha de creación del código de recuperación', null=True),
        ),
    ]
