# Generated by Django 4.2.27 on 2026-02-24 03:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioWeb',
            fields=[
                ('id_servicio_web', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio al público')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios_web/imagenes/', verbose_name='Imagen del Servicio (opcional)')),
                ('video', models.FileField(blank=True, null=True, upload_to='servicios_web/videos/', verbose_name='Video del Servicio (opcional)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Servicio Web',
                'verbose_name_plural': 'Servicios Web',
                'ordering': ['nombre'],
            },
        ),
    ]
