# Generated by Django 4.2.27 on 2026-03-07 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_video'),
        ('servicios_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioweb',
            name='servicio_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_web', to='servicios.servicio', verbose_name='Servicio origen'),
        ),
    ]
