# Generated by Django 4.2.27 on 2026-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='rol',
            field=models.CharField(choices=[('AUX', 'Auxiliar'), ('COL', 'Colaborador'), ('ADM', 'Administrador')], max_length=3, verbose_name='Rol'),
        ),
    ]
