# Generated by Django 4.2.27 on 2026-02-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='apellidos',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos'),
            preserve_default=False,
        ),
    ]
