# Generated by Django 4.2.27 on 2025-12-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_compra', models.IntegerField(blank=True, help_text='Código de compra asociado', null=True)),
                ('codigo_cliente', models.IntegerField(blank=True, help_text='Código de cliente asociado', null=True)),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=60, verbose_name='Nombre del Producto')),
                ('precio', models.IntegerField(help_text='Precio del producto en pesos colombianos', verbose_name='Precio')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('linea', models.CharField(blank=True, help_text='Línea o categoría del producto', max_length=45, verbose_name='Línea')),
                ('presentacion', models.CharField(blank=True, help_text='Presentación del producto (ej: 500ml, caja x12)', max_length=50, verbose_name='Presentación')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('metro', 'Metro')], default='unidad', help_text='Unidad de medida del producto', max_length=45, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado'), ('en_transito', 'En Tránsito')], default='disponible', help_text='Estado actual del producto', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_marca', models.ForeignKey(help_text='Marca del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='Productos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='Productos_p_nombre_3c70d2_idx'), models.Index(fields=['estado'], name='Productos_p_estado_aad184_idx'), models.Index(fields=['linea'], name='Productos_p_linea_c2718c_idx')],
            },
        ),
    ]
