# Generated by Django 4.2.27 on 2026-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
