# Generated by Django 4.2.27 on 2026-01-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_descripcion_alter_producto_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_cliente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_compra',
        ),
    ]
