# Generated by Django 4.2.27 on 2026-02-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_remove_producto_id_marca_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado'), ('en_transito', 'En Tránsito'), ('inactivo', 'Inactivo')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
