# Generated by Django 4.2.27 on 2026-02-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado'), ('en_transito', 'En Tránsito')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
