# Generated by Django 4.2.27 on 2026-02-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_producto_activo_alter_producto_estado'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producto',
            name='Productos_p_estado_aad184_idx',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
