# Generated by Django 4.2.27 on 2026-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_remove_producto_productos_p_estado_aad184_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
