# Generated by Django 4.2.27 on 2026-02-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_alter_producto_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
