# Generated by Django 4.2.27 on 2026-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_marca_imagen_marca_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
