# Generated by Django 4.2.27 on 2026-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado (soft-delete)'),
        ),
    ]
