# Generated by Django 4.2.27 on 2026-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='anulada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
