# Generated by Django 4.2.27 on 2026-02-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
