# Generated by Django 4.2.27 on 2026-02-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_precio_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_anulada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
