# Generated by Django 4.2.27 on 2026-02-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compra_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='compras.compra'),
        ),
    ]
