# Generated by Django 4.2.27 on 2026-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='apellido_repartidor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cedula_repartidor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='nombre_repartidor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='telefono_repartidor',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='tipo_vehiculo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
    ]
