# Generated by Django 4.2.27 on 2026-03-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_fix_anulada_columns'),
        ('compras', '0003_compra_fecha_anulada'),
    ]

    operations = [
    ]
