# Generated by Django 4.2.27 on 2026-01-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('id_venta', models.CharField(max_length=50)),
                ('codigo_marca', models.CharField(max_length=50)),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('fecha_entrega', models.DateField()),
                ('cc_encargado', models.CharField(max_length=20)),
                ('nombre_encargado', models.CharField(max_length=150)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('placa_vehiculo', models.CharField(max_length=20)),
                ('telefono_proveedor', models.CharField(max_length=20)),
                ('correo_proveedor', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
    ]
