# Generated by Django 4.2.27 on 2026-01-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_alter_proveedor_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre_proveedor'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cc_encargado',
            field=models.CharField(max_length=20, verbose_name='Cédula encargado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_marca',
            field=models.CharField(max_length=50, verbose_name='Código Marca'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo_proveedor',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_venta',
            field=models.CharField(max_length=50, verbose_name='ID Venta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=20, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_encargado',
            field=models.CharField(max_length=150, verbose_name='Nombre encargado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=150, unique=True, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='placa_vehiculo',
            field=models.CharField(max_length=20, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_proveedor',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_vehiculo',
            field=models.CharField(max_length=100, verbose_name='Tipo de vehículo'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nombre_proveedor'], name='Proveedores_nombre__d083d7_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nit'], name='Proveedores_nit_cf99e8_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='Proveedores_estado_b8ba9d_idx'),
        ),
    ]
