# Generated by Django 4.2.27 on 2026-02-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0003_alter_proveedor_options_alter_proveedor_cc_encargado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cc_encargado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='codigo_marca',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='id_venta',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_encargado',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='tipo_vehiculo',
        ),
    ]
