# Generated by Django 4.2.27 on 2026-02-22 07:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionDatos',
            fields=[
                ('id_gestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_servicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio del Servicio')),
                ('es_oferta_especial', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Es una oferta especial?')),
                ('descripcion_oferta', models.TextField(blank=True, null=True, verbose_name='¿Cuál es la promoción?')),
                ('anticipo_cliente', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo realizado por el cliente')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('medio_virtual', 'Medio Virtual')], max_length=20, verbose_name='Medio de pago')),
                ('saldo_pendiente', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo pendiente por pagar')),
                ('procedimiento_realizado_por', models.CharField(max_length=200, verbose_name='Procedimiento realizado por')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo_tratamiento', models.TextField(verbose_name='Tipo de tratamiento a realizar')),
                ('requiere_resellado', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Requiere resellado?')),
                ('porcentaje_tratamiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje del tratamiento')),
                ('porosidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Porosidad')),
                ('textura', models.CharField(choices=[('gruesa', 'Gruesa'), ('normal', 'Normal'), ('delgada', 'Delgada')], max_length=10, verbose_name='Textura')),
                ('forma_natural', models.CharField(choices=[('liso', 'Liso'), ('ondulado', 'Ondulado'), ('rizado', 'Rizado'), ('afro', 'Afro')], max_length=15, verbose_name='Forma Natural')),
                ('elasticidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('no_presenta', 'No Presenta')], max_length=15, verbose_name='Elasticidad')),
                ('longitud', models.CharField(choices=[('corto', 'Corto'), ('medio', 'Medio'), ('largo', 'Largo'), ('extra_largo', 'Extra Largo')], max_length=15, verbose_name='Longitud')),
                ('densidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10, verbose_name='Densidad o Cantidad')),
                ('piel_cabelludo', models.CharField(choices=[('grasa', 'Grasa'), ('normal', 'Normal'), ('seca', 'Seca')], max_length=10, verbose_name='Piel Cabelludo')),
                ('nivel_alopecia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('no_presenta', 'No Presenta')], max_length=15, verbose_name='Alopecia')),
                ('nivel_caida', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('no_presenta', 'No Presenta')], max_length=15, verbose_name='Caída de Cabello')),
                ('nivel_caspa', models.CharField(choices=[('cronica', 'Crónica'), ('media', 'Media'), ('baja', 'Baja'), ('no_presenta', 'No Presenta')], max_length=15, verbose_name='Caspa')),
                ('lactante', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Lactante?')),
                ('gestante', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Gestante?')),
                ('tratamiento_quimico', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Ha tenido algún tratamiento químico?')),
                ('tipo_tratamiento_quimico', models.TextField(blank=True, null=True, verbose_name='¿Qué tipo de tratamiento químico?')),
                ('tiempo_tratamiento_quimico', models.TextField(blank=True, null=True, verbose_name='¿Hace cuánto tiempo?')),
                ('plancha_cabello', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Se plancha el cabello?')),
                ('uso_plancha', models.TextField(blank=True, null=True, verbose_name='Uso de plancha')),
                ('tiempo_uso_plancha', models.TextField(blank=True, null=True, verbose_name='¿Hace cuánto usa plancha?')),
                ('tinte_cabello', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Se tiñe el cabello?')),
                ('tipo_tinte', models.TextField(blank=True, null=True, verbose_name='Tipo de tinte')),
                ('tiempo_tinte', models.TextField(blank=True, null=True, verbose_name='¿Hace cuánto se tiñe?')),
                ('tratamiento_actual', models.TextField(blank=True, null=True, verbose_name='¿Qué tratamiento capilar lleva actualmente en casa?')),
                ('procesos_tintura', models.BooleanField(default=False, verbose_name='Tintura')),
                ('procesos_decoloracion', models.BooleanField(default=False, verbose_name='Decoloración')),
                ('procesos_ondulados', models.BooleanField(default=False, verbose_name='Ondulados Perm')),
                ('procesos_extracciones', models.BooleanField(default=False, verbose_name='Extracciones')),
                ('procesos_alisados', models.BooleanField(default=False, verbose_name='Alisados')),
                ('procesos_super_aclarante', models.BooleanField(default=False, verbose_name='Super Aclarante')),
                ('procesos_otro', models.TextField(blank=True, null=True, verbose_name='Otro proceso químico')),
                ('cuenta_con_secador', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Cuenta con secador?')),
                ('frecuencia_recoge_cabello', models.TextField(verbose_name='¿Cada cuánto recoge su cabello?')),
                ('realiza_ejercicio', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Realiza ejercicio o algún tipo de deporte?')),
                ('frecuencia_ejercicio', models.TextField(blank=True, null=True, verbose_name='¿Cuántas veces a la semana hace deporte?')),
                ('usa_casco', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Debe usar algún casco?')),
                ('productos_capilares', models.TextField(verbose_name='Marca shampoo, acondicionador y mascarilla que utiliza')),
                ('se_bana_agua_caliente', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Se baña con agua caliente?')),
                ('requiere_refuerzo', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Requiere refuerzo del tratamiento en 15 días?')),
                ('sufre_tiroides', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Sufre de tiroides o toma medicamentos para la tiroides?')),
                ('medicamento_tiroides', models.TextField(blank=True, null=True, verbose_name='¿Qué medicamento?')),
                ('despunte_hoy', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Se realizará el día de hoy despunte?')),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='gestion_datos/fotos/', verbose_name='Foto antes del tratamiento')),
                ('foto_despues', models.ImageField(blank=True, null=True, upload_to='gestion_datos/fotos/', verbose_name='Foto después del tratamiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones generales')),
                ('recomendaciones_post_cuidados', models.TextField(verbose_name='Recomendaciones o anotaciones sobre post cuidados')),
                ('firma_consentimiento', models.ImageField(blank=True, null=True, upload_to='gestion_datos/firmas/', verbose_name='Firma del consentimiento informado')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_datos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Gestión de Datos del Cliente',
                'verbose_name_plural': 'Gestión de Datos de Clientes',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
